blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://refacto-studio.github.io/react-native-swipeable-stack/
    about: Check the docs for guides and API reference
  - name: ðŸ’¬ Discussions
    url: https://github.com/Refacto-Studio/react-native-swipeable-stack/discussions
    about: Ask questions and share ideas
